;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	c-electric-semi&comma
	helm-M-x
	kmacro-start-macro-or-insert-counter
	paredit-backward-kill-word
	paredit-doublequote
	paredit-forward-delete
	paredit-forward-slurp-sexp
	smex
	))

(setq mc/cmds-to-run-once
      '(
	TeX-command-master
	rgrep
	))
