;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; macros de Sylvie Ruette avec contribution de Vincent Belaïche
;; et correction de Takéo Takahashi.
;; version décembre 2011.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; accents-tex : change les caracteres accentues en accents tex
;; conserve les majuscules, sans demander confirmation
;;
;; tex-accents : change les accents tex en caracteres accentues
;; sans demander confirmation
;; les majuscules sont respectees

(defun accents-tex ()
  (interactive)
  "change les caracteres accentues en accents tex"
  (save-excursion
  (beginning-of-buffer)
  (replace-string "\á" "\\'a")
  (beginning-of-buffer)
  (replace-string "\à" "\\`a")
  (beginning-of-buffer)
  (replace-string "\â" "\\^a")
  (beginning-of-buffer)
  (replace-string "\ä" "\\\"a")
  (beginning-of-buffer)
  (replace-string "\é" "\\'e")
  (beginning-of-buffer)
  (replace-string "\è" "\\`e")
  (beginning-of-buffer)
  (replace-string "\ê" "\\^e")
  (beginning-of-buffer)
  (replace-string "\ë" "\\\"e")
  (beginning-of-buffer)
  (replace-string "\ó" "\\'o")
  (beginning-of-buffer)
  (replace-string "\ò" "\\`o")
  (beginning-of-buffer)
  (replace-string "\ô" "\\^o")
  (beginning-of-buffer)
  (replace-string "\ö" "\\\"o")
  (beginning-of-buffer)
  (replace-string "\ú" "\\'u")
  (beginning-of-buffer)
  (replace-string "\ù" "\\`u")
  (beginning-of-buffer)
  (replace-string "\û" "\\^u")
  (beginning-of-buffer)
  (replace-string "\ü" "\\\"u")
  (beginning-of-buffer)
  (replace-string "\ç" "\\c{c}")
  (beginning-of-buffer)
  (replace-string "\Í" "\\'I")
  (beginning-of-buffer)
  (replace-string "\Ì" "\\`I")
  (beginning-of-buffer)
  (replace-string "\Î" "\\^I")
  (beginning-of-buffer)
  (replace-string "\Ï" "\\\"I")
  (beginning-of-buffer)
  (replace-string "\í" "\\'{\\i}")
  (beginning-of-buffer)
  (replace-string "\ì" "\\`{\\i}")
  (beginning-of-buffer)
  (replace-string "\î" "\\^{\\i}")
  (beginning-of-buffer)
  (replace-string "\ï" "\\\"{\\i}")
))

(defun tex-accents ()
  (interactive)
  "change les caracteres accentues en accents tex"
  (save-excursion
  (beginning-of-buffer)
  (replace-string "\\'A" "\Á")
  (beginning-of-buffer)
  (replace-string "\\`A" "\À")
  (beginning-of-buffer)
  (replace-string "\\^A" "\Â")
  (beginning-of-buffer)
  (replace-string "\\\"A" "\Ä")
  (beginning-of-buffer)
  (replace-string "\\'E" "\É")
  (beginning-of-buffer)
  (replace-string "\\`E" "\È")
  (beginning-of-buffer)
  (replace-string "\\^E" "\Ê" )
  (beginning-of-buffer)
  (replace-string "\\\"E" "\Ë")
  (beginning-of-buffer)
  (replace-string "\\'I" "\Í")
  (beginning-of-buffer)
  (replace-string "\\`I" "\Ì")
  (beginning-of-buffer)
  (replace-string "\\^I" "\Î")
  (beginning-of-buffer)
  (replace-string "\\\"I" "\Ï")
  (beginning-of-buffer)
  (replace-string "\\'O" "\0")
  (beginning-of-buffer)
  (replace-string "\\`O" "\Ò")
  (beginning-of-buffer)
  (replace-string "\\^O" "\Ô")
  (beginning-of-buffer)
  (replace-string "\\\"O" "\Ö")
  (beginning-of-buffer)
  (replace-string "\\'U" "\Ú")
  (beginning-of-buffer)
  (replace-string "\\`U" "\Ù")
  (beginning-of-buffer)
  (replace-string "\\^U" "\Û")
  (beginning-of-buffer)
  (replace-string "\\\"U" "\Ü")
  (beginning-of-buffer)
  (replace-string "\\c{C}" "\Ç")
  (beginning-of-buffer)
  (replace-string "\\c C" "\Ç")
  (beginning-of-buffer)
  (replace-string "\\'a" "\á" )
  (beginning-of-buffer)
  (replace-string "\\`a" "\à" )
  (beginning-of-buffer)
  (replace-string "\\^a" "\â" )
  (beginning-of-buffer)
  (replace-string "\\\"a" "\ä" )
  (beginning-of-buffer)
  (replace-string "\\'e" "\é" )
  (beginning-of-buffer)
  (replace-string "\\`e" "\è")
  (beginning-of-buffer)
  (replace-string "\\^e" "\ê")
  (beginning-of-buffer)
  (replace-string "\\\"e" "\ë")
  (beginning-of-buffer)
  (replace-string "\\'{\\i}" "\í")
  (beginning-of-buffer)
  (replace-string "\\`{\\i}" "\ì")
  (beginning-of-buffer)
  (replace-string "\\^{\\i}" "\î")
  (beginning-of-buffer)
  (replace-string "\\\"{\\i}" "\ï")
  (beginning-of-buffer)
  (replace-string "\\'\\i" "\í")
  (beginning-of-buffer)
  (replace-string "\\`\\i" "\ì")
  (beginning-of-buffer)
  (replace-string "\\^\\i" "\î")
  (beginning-of-buffer)
  (replace-string "\\\"\\i" "\ï")
  (beginning-of-buffer)
  (replace-string "\\'o" "\ó")
  (beginning-of-buffer)
  (replace-string "\\`o" "\ò")
  (beginning-of-buffer)
  (replace-string "\\^o" "\ô")
  (beginning-of-buffer)
  (replace-string "\\\"o" "\ö")
  (beginning-of-buffer)
  (replace-string  "\\'u" "\ú")
  (beginning-of-buffer)
  (replace-string "\\`u" "\ù")
  (beginning-of-buffer)
  (replace-string "\\^u" "\û")
  (beginning-of-buffer)
  (replace-string "\\\"u" "\ü")
  (beginning-of-buffer)
  (replace-string "\\c{c}" "\ç")
  (beginning-of-buffer)
  (replace-string "\\c c" "\ç")
))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; accents-html : change les caracteres accentues en accents html
;; sans demander confirmation
;; les majuscules sont respectees
;;
;; html-accents : change les accents html en caracteres accentues
;; sans demander confirmation
;; les majuscules sont respectees

(defun accents-html ()
  (interactive)
  "change les caracteres accentues en accents html"
  (save-excursion
  (beginning-of-buffer)
  (replace-string "\Á" "&Aacute;")
  (beginning-of-buffer)
  (replace-string "\À" "&Agrave;")
  (beginning-of-buffer)
  (replace-string "\Â" "&Acirc;")
  (beginning-of-buffer)
  (replace-string "\Ä" "&Auml;")
  (beginning-of-buffer)
  (replace-string "\É" "&Eacute;")
  (beginning-of-buffer)
  (replace-string "È" "&Egrave;")
  (beginning-of-buffer)
  (replace-string "\Ê" "&Ecirc;")
  (beginning-of-buffer)
  (replace-string "\Ë" "&Euml;")
  (beginning-of-buffer)
  (replace-string "\Í" "&Iacute;")
  (beginning-of-buffer)
  (replace-string "\Ì" "&Igrave;")
  (beginning-of-buffer)
  (replace-string "\Î" "&Icirc;")
  (beginning-of-buffer)
  (replace-string "\Ï" "&Iuml;")
  (beginning-of-buffer)
  (replace-string "\Ó" "&Oacute;")
  (beginning-of-buffer)
  (replace-string "\Ò" "&Ograve;")
  (beginning-of-buffer)
  (replace-string "\Ô" "&Ocirc;")
  (beginning-of-buffer)
  (replace-string "\Ö" "&Ouml;")
  (beginning-of-buffer)
  (replace-string "\Ú" "&Uacute")
  (beginning-of-buffer)
  (replace-string "\Ù" "&Ugrave;")
  (beginning-of-buffer)
  (replace-string "\Û" "&Ucirc;")
  (beginning-of-buffer)
  (replace-string "\Ü" "&Uuml;")
  (beginning-of-buffer)
  (replace-string "\Ç" "&Ccedil;")
  (beginning-of-buffer)
  (replace-string "\á" "&aacute;")
  (beginning-of-buffer)
  (replace-string "\à" "&agrave;")
  (beginning-of-buffer)
  (replace-string "\â" "&acirc;")
  (beginning-of-buffer)
  (replace-string "\ä" "&auml;")
  (beginning-of-buffer)
  (replace-string "\é" "&eacute;")
  (beginning-of-buffer)
  (replace-string "\è" "&egrave;")
  (beginning-of-buffer)
  (replace-string "\ê" "&ecirc;")
  (beginning-of-buffer)
  (replace-string "\ë" "&euml;")
  (beginning-of-buffer)
  (replace-string "\í" "&iacute;")
  (beginning-of-buffer)
  (replace-string "\ì" "&igrave;")
  (beginning-of-buffer)
  (replace-string "\î" "&icirc;")
  (beginning-of-buffer)
  (replace-string "\ï" "&iuml;")
  (beginning-of-buffer)
  (replace-string "\ó" "&oacute;")
  (beginning-of-buffer)
  (replace-string "\ò" "&ograve;")
  (beginning-of-buffer)
  (replace-string "\ô" "&ocirc;")
  (beginning-of-buffer)
  (replace-string "\ö" "&ouml;")
  (beginning-of-buffer)
  (replace-string "\ú" "&uacute")
  (beginning-of-buffer)
  (replace-string "\ù" "&ugrave;")
  (beginning-of-buffer)
  (replace-string "\û" "&ucirc;")
  (beginning-of-buffer)
  (replace-string "\ü" "&uuml;")
  (beginning-of-buffer)
  (replace-string "\ç" "&ccedil;")

))

(defun html-accents ()
  (interactive)
  "change les accents html en caracteres accentues"
  (save-excursion
  (beginning-of-buffer)
  (replace-string "&Aacute;" "\Á")
  (beginning-of-buffer)
  (replace-string "&Agrave;" "\À")
  (beginning-of-buffer)
  (replace-string "&Acirc;" "\Â")
  (beginning-of-buffer)
  (replace-string "&Auml;" "\Ä")
  (beginning-of-buffer)
  (replace-string "&Eacute;" "\É")
  (beginning-of-buffer)
  (replace-string "&Egrave;" "\È")
  (beginning-of-buffer)
  (replace-string "&Ecirc;" "\Ê")
  (beginning-of-buffer)
  (replace-string "&Euml;" "\Ë")
  (beginning-of-buffer)
  (replace-string "&Iacute;" "\Í")
  (beginning-of-buffer)
  (replace-string "&Igrave;" "\Ì")
  (beginning-of-buffer)
  (replace-string "&Icirc;" "\Î")
  (beginning-of-buffer)
  (replace-string "&Iuml;" "\Ï")
  (beginning-of-buffer)
  (replace-string "&Oacute;" "\Ó")
  (beginning-of-buffer)
  (replace-string "&Ograve;" "\Ò")
  (beginning-of-buffer)
  (replace-string "&Ocirc;" "\Ô")
  (beginning-of-buffer)
  (replace-string "&Ouml;" "\Ö")
  (beginning-of-buffer)
  (replace-string "&Uacute;" "\Ú")
  (beginning-of-buffer)
  (replace-string "&Ugrave;" "\Ù")
  (beginning-of-buffer)
  (replace-string "&Ucirc;" "\Û")
  (beginning-of-buffer)
  (replace-string "&Uuml;" "\Ü")
  (beginning-of-buffer)
  (replace-string "&Ccedil;" "\Ç")
  (beginning-of-buffer)
  (replace-string "&aacute;" "\á")
  (beginning-of-buffer)
  (replace-string "&agrave;" "\à")
  (beginning-of-buffer)
  (replace-string "&acirc;" "\â")
  (beginning-of-buffer)
  (replace-string "&auml;" "\ä")
  (beginning-of-buffer)
  (replace-string "&eacute;" "\é")
  (beginning-of-buffer)
  (replace-string "&egrave;" "\è")
  (beginning-of-buffer)
  (replace-string "&ecirc;" "\ê")
  (beginning-of-buffer)
  (replace-string "&euml;" "\ë")
  (beginning-of-buffer)
  (replace-string "&iacute;" "\í")
  (beginning-of-buffer)
  (replace-string "&igrave;" "\ì")
  (beginning-of-buffer)
  (replace-string "&icirc;" "\î")
  (beginning-of-buffer)
  (replace-string "&iuml;" "\ï")
  (beginning-of-buffer)
  (replace-string "&oacute;" "\ó")
  (beginning-of-buffer)
  (replace-string "&ograve;" "\ò")
  (beginning-of-buffer)
  (replace-string "&ocirc;" "\ô")
  (beginning-of-buffer)
  (replace-string "&ouml;" "\ö")
  (beginning-of-buffer)
  (replace-string "&uacute;" "\ú")
  (beginning-of-buffer)
  (replace-string "&ugrave;" "\ù")
  (beginning-of-buffer)
  (replace-string "&ucirc;" "\û")
  (beginning-of-buffer)
  (replace-string "&uuml;" "\ü")
  (beginning-of-buffer)
  (replace-string "&ccedil;" "\ç")
))
